-- 코드를 입력하세요
SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, (fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN (
    SELECT PRODUCT_ID, DATE_FORMAT(IN_DATE,'%Y-%m-%d'), SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc